// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase URL/anon key는 클라이언트 번들에 노출되는 공개값이므로 하드코딩.
// Service role key는 절대 여기 두지 말 것 — Edge Function 환경변수로만 사용.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://bnhnaaarsyauppdbrbco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaG5hYWFyc3lhdXBwZGJyYmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxODc5NzMsImV4cCI6MjA4OTc2Mzk3M30.Cbd6nbPGuOMHfZ7oHDTmAhMgx_luVxh1gDyFO4UqfYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
